language: python

services: 
  - postgresql
python:
    - "3.6"

# Install dependencies
install:
    - pip3 install pytest
    - pip3 install pytest-cov
    - pip3 install coveralls
    - pip3 install -r requirements.txt
before_script: 

  - psql -c "CREATE DATABASE test_questioner;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres;" -U postgres
 
# Run tests
script:
    - pytest --cov=app

after_success:
    - coveralls


    